
#numbers = [3,51,2,8,6]

#print(sorted(numbers, reverse=True))
#print(numbers)

#items = [("Product 1", 123),
         #"Product 2", 12),
         #("Product 3", 8123)]

#def sort_item(item):
    #return item[1]
#items.sort(key=lambda item:item[1])
#print(items)

#students = [
    #{"imie":"Jan","wiek": 20},
#{"imie":"Juan","wiek": 15},
#{"imie":"Joan","wiek": 185}]

#students.sort(key = lambda kaczucha:kaczucha["wiek"])

#print(students)
